### ISSUE TITLE
Autoplay my stream

### ISSUE THREAD

**Issue by Abdallahsamy1** [schollz/streammyaudio#14]
Can you make the stream autoplay in browser once the listener opens the link the stream automatically play or the mp3 url autoplay?
Thanks for the great website and the great tool

**Comment by schollz** [comment]
sounds great, please make a pr

**Comment by Abdallahsamy1** [comment]
also I'm asking if there is an ability to stream in (MPEG) transport stream as I'm planning to broadcast an online radio that would work in STB recievers that only supports .ts instead of mp3 is that possible ?

**Comment by schollz** [comment]
yes sounds possible!

**Comment by Abdallahsamy1** [comment]
how can I do this or will you release a new version with these updates ?

**Comment by schollz** [comment]
go to the source code and make all the edits you want!
